const mix = require('laravel-mix');
const glob = require('glob');
const fs = require('fs');
const exec = require('child_process').exec;
require('laravel-mix-nunjucks')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for your application, as well as bundling up your JS files.
 |
 */
 
/**
 * Compile HTML (Nunjucks compiler)
 */
mix.njk('src/html/**/*', 'dist/', {
  ext: '.html',
  data: {
    version: '3.0.0',
    site_name: 'Stisla'
  },
  // marked: null,
  envOptions: {
  	trimBlocks: true,
  	lstripBlocks: true,
  },
  manageEnv: (nunjucks) => {
  	nunjucks.addFilter('is_active', (str, reg, page) => {
		reg = new RegExp(reg, 'gm');
		reg = reg.exec(page);

		if(reg != null) {
			return str;
		}
	})
  },
});

/**
 * Compile CSS (SCSS compiler)
 */
mix.sass('src/scss/style.scss', 'dist/css');

/**
 * Compile JS (Babel compiler)
 */

// get all js files
const jsFiles = glob.sync('src/js/**/*.js');

// compile each js file
jsFiles.forEach(filename => {
	mix.js(filename, filename.replace(/^src\//g, 'dist/'));
});

/**
 * Publish dependencies from node modules
 */
const libs = JSON.parse(fs.readFileSync('json/libraries.json'));

exec('mkdir -p dist/libraries');

libs.forEach((lib) => {
	let path = `dist/libraries/${lib}`;
	let cmd = `cp -r node_modules/${lib} ${path}`;

	exec(cmd);
});

/**
 * Copying all imgs from src
 */
mix.copyDirectory('src/img', 'dist/img');


/**
 * Watch
 */
mix.browserSync({
	proxy: false,
	files: [
	    'src/html/*',
	    'src/scss/*',
	    'src/js/*',
	],
	server: {
		baseDir: 'dist'
	}
});

// Full API
// mix.js(src, output);
// mix.react(src, output); <-- Identical to mix.js(), but registers React Babel compilation.
// mix.preact(src, output); <-- Identical to mix.js(), but registers Preact compilation.
// mix.coffee(src, output); <-- Identical to mix.js(), but registers CoffeeScript compilation.
// mix.ts(src, output); <-- TypeScript support. Requires tsconfig.json to exist in the same folder as webpack.mix.js
// mix.extract(vendorLibs);
// mix.sass(src, output);
// mix.less(src, output);
// mix.stylus(src, output);
// mix.postCss(src, output, [require('postcss-some-plugin')()]);
// mix.browserSync('my-site.test');
// mix.combine(files, destination);
// mix.babel(files, destination); <-- Identical to mix.combine(), but also includes Babel compilation.
// mix.copy(from, to);
// mix.copyDirectory(fromDir, toDir);
// mix.minify(file);
// mix.sourceMaps(); // Enable sourcemaps
// mix.version(); // Enable versioning.
// mix.disableNotifications();
// mix.setPublicPath('path/to/public');
// mix.setResourceRoot('prefix/for/resource/locators');
// mix.autoload({}); <-- Will be passed to Webpack's ProvidePlugin.
// mix.webpackConfig({}); <-- Override webpack.config.js, without editing the file directly.
// mix.babelConfig({}); <-- Merge extra Babel configuration (plugins, etc.) with Mix's default.
// mix.then(function () {}) <-- Will be triggered each time Webpack finishes building.
// mix.override(function (webpackConfig) {}) <-- Will be triggered once the webpack config object has been fully generated by Mix.
// mix.dump(); <-- Dump the generated webpack config object to the console.
// mix.extend(name, handler) <-- Extend Mix's API with your own components.
// mix.options({
//   extractVueStyles: false, // Extract .vue component styling to file, rather than inline.
//   globalVueStyles: file, // Variables file to be imported in every component.
//   processCssUrls: true, // Process/optimize relative stylesheet url()'s. Set to false, if you don't want them touched.
//   purifyCss: false, // Remove unused CSS selectors.
//   terser: {}, // Terser-specific options. https://github.com/webpack-contrib/terser-webpack-plugin#options
//   postCss: [] // Post-CSS options: https://github.com/postcss/postcss/blob/master/docs/plugins.md
// });
